# @package _global_.model
type: "transformer_classifier"

_target_: ai_generated_text_detection.model.transformer_classifier.TransformerClassifier

params:
  vocab_size: 5000
  embedding_dim: 128  # d_model
  num_heads: 4        # nhead
  num_layers: 3
  hidden_dim: 256     # dim_feedforward
  dropout: 0.1
  num_classes: 2
